version: '3.8'

services:
  webservice:
    image: devopsdockeruh/simple-web-service
    ports:
    - 8080:8080
    volumes:
      - ${PWD}/upload/text.log/:/usr/src/app/text.log
    command: ["server"]
