services:
  express:
    image: astranero/express-app:latest
    ports:
    - 8080:8080
    labels:
    - "com.containrrr.watchtower.enable=true"
    - "com.containrrr.watchtower.cleanup=true"

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP
      - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    depends_on:
      - express
    command:  --cleanup --label-enable
